### ISSUE TITLE
package.json of eslint-config-airbnb is not correct

### ISSUE THREAD

**Issue by lyz810** [airbnb/javascript#2529]
version: eslint-config-airbnb@19.0.3
package.json in source code is correct, but package.json info in npm is wrong as follow:
https://registry.npmjs.com/eslint-config-airbnb/19.0.3

dependencies fields in package.json 
```
  "dependencies": {
    "eslint-config-airbnb-base": "file:../eslint-config-airbnb-base",
    "object.assign": "^4.1.2",
    "object.entries": "^1.1.5"
  }
```
It will not install eslint-config-airbnb-base when install `eslint-config-airbnb` package
reproduce:
`npm install eslint-config-airbnb@19.0.3` and check `node_modules`, if `eslint-config-airbnb-base` package will be found

In previous version 19.0.2, version of `eslint-config-airbnb-base` is `^15.0.0` and worked well

Could you republish a new version to this issue?

**Comment by pupboss** [comment]
surprise for christmas

**Comment by billnbell** [comment]
this one needs to be fixed ASAP

**Comment by natelindev** [comment]
can reproduce, this is a big error

**Comment by ahmafi** [comment]
I get the error `Error: Cannot find module 'eslint-config-airbnb-base'` after updating to 19.0.3

**Comment by ljharb** [comment]
Indeed, I’ll fix this shortly.

**Comment by ljharb** [comment]
Marked v19.0.2 as latest; and then published v19.0.4 which should fix it.

**Comment by ljharb** [comment]
For posterity, this was caused by https://github.com/npm/cli/issues/3619.
